cc_library(
    name = "TreesContainer",
    srcs = ["TreeContainer.cpp"],
    hdrs = ["TreeContainer.hpp"],
    deps = ["//src/FruitTree:FruitTree", "//src/ForestTree:ForestTree"],
    visibility = ["//visibility:public"],
)
