cc_test(
    name = "tests",
    srcs = ["test.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//src/TreesContainer:TreesContainer",
        "//src/Professor:Professor",
        "//src/Student:Student",
        "//src/StudentSecondSession:StudentSecondSession"
    ]
)
