cc_library(
    name = "classFolder",
    srcs = [
        "UsualFraction.cpp",
        "Matrix.cpp"
    ],
    hdrs = [
        "UsualFraction.hpp",
        "Matrix.hpp"
    ],
    visibility = ["//visibility:public"],
)
