cc_library(
    name = "classFolder",
    srcs = [
        "usualFraction.cpp",
        "matrix.cpp"
    ],
    hdrs = [
        "usualFraction.hpp",
        "matrix.hpp"
    ],
    visibility = ["//visibility:public"],
)