cc_binary(
    name = "cpp_app",
    srcs = ["main.cpp"],
    deps = [
        "//src/TreesContainer:TreesContainer",
        "//src/Professor:Professor",
        "//src/Student:Student",
        "//src/StudentSecondSession:StudentSecondSession"
    ],
    data = ["//src/files:files"],
)
