cc_library(
    name = "classFolder",
    srcs = [
        "person.cpp",
        "student.cpp",
        "professor.cpp",
        "studentBeforeSession.cpp",
        "studentAfterFirstSession.cpp",
        "studentAfterSecondSession.cpp",
        "tree.cpp",
        "forestTree.cpp",
        "fruitTree.cpp",
        "treeContainer.cpp",

    ],
    hdrs = [
        "person.hpp",
        "student.hpp",
        "professor.hpp",
        "studentBeforeSession.hpp",
        "studentAfterFirstSession.hpp",
        "studentAfterSecondSession.hpp",
        "tree.hpp",
        "forestTree.hpp",
        "fruitTree.hpp",
        "treeContainer.hpp",
        
    ],
    visibility = ["//visibility:public"],
)