cc_library(
    name = "classFolder",
    srcs = [
        "person.cpp",
        "student.cpp",
        "professor.cpp",

    ],
    hdrs = [
        "person.hpp",
        "student.hpp",
        "professor.hpp",

    ],
    visibility = ["//visibility:public"],
)