cc_library(
    name = "classFolder",
    srcs = [
        "person.cpp",
        "student.cpp",
        "professor.cpp",
        "studentBeforeSession.cpp",
        "studentAfterFirstSession.cpp",
        "studentAfterSecondSession.cpp"
    ],
    hdrs = [
        "person.hpp",
        "student.hpp",
        "professor.hpp",
        "studentBeforeSession.hpp",
        "studentAfterFirstSession.hpp",
        "studentAfterSecondSession.hpp"
    ],
    visibility = ["//visibility:public"],
)