cc_test(
    name = "tests",
    srcs = ["test.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//src/Stack:Stack",
        "//src/Wagon:Wagon",
        "//src/NSDeque:NSDeque"
    ]
)
